clubs_champions_ligue_2024 = {
    "Arsenal FC": {"ShortenName": "Arsenal", "Country": "ENG", "Points": 0},
    "Aston Villa FC": {"ShortenName": "Aston Villa", "Country": "ENG", "Points": 0},
    "Atalanta BC": {"ShortenName": "Atalanta", "Country": "ITA", "Points": 0},
    "Atlético de Madrid": {"ShortenName": "Atleti", "Country": "ESP", "Points": 0},
    "Borussia Dortmund": {"ShortenName": "B. Dortmund", "Country": "GER", "Points": 0},
    "FC Barcelona": {"ShortenName": "Barcelona", "Country": "ESP", "Points": 0},
    "FC Bayern München": {"ShortenName": "Bayern München", "Country": "GER", "Points": 0},
    "SL Benfica": {"ShortenName": "Benfica", "Country": "POR", "Points": 0},
    "Bologna FC 1909": {"ShortenName": "Bologna", "Country": "ITA", "Points": 0},
    "Stade Brestois 29": {"ShortenName": "Brest", "Country": "FRA", "Points": 0},
    "Celtic FC": {"ShortenName": "Celtic", "Country": "SCO", "Points": 0},
    "Club Brugge KV": {"ShortenName": "Club Brugge", "Country": "BEL", "Points": 0},
    "FK Crvena Zvezda": {"ShortenName": "Crvena Zvezda", "Country": "SRB", "Points": 0},
    "Feyenoord": {"ShortenName": "Feyenoord", "Country": "NED", "Points": 0},
    "Girona FC": {"ShortenName": "Girona", "Country": "ESP", "Points": 0},
    "GNK Dinamo": {"ShortenName": "GNK Dinamo", "Country": "CRO", "Points": 0},
    "FC Internazionale Milano": {"ShortenName": "Inter", "Country": "ITA", "Points": 0},
    "Juventus": {"ShortenName": "Juventus", "Country": "ITA", "Points": 0},
    "RB Leipzig": {"ShortenName": "Leipzig", "Country": "GER", "Points": 0},
    "Bayer 04 Leverkusen": {"ShortenName": "Leverkusen", "Country": "GER", "Points": 0},
    "LOSC Lille": {"ShortenName": "Lille", "Country": "FRA", "Points": 0},
    "Liverpool FC": {"ShortenName": "Liverpool", "Country": "ENG", "Points": 0},
    "Manchester City": {"ShortenName": "Man City", "Country": "ENG", "Points": 0},
    "AC Milan": {"ShortenName": "Milan", "Country": "ITA", "Points": 0},
    "AS Monaco": {"ShortenName": "Monaco", "Country": "FRA", "Points": 0},
    "Paris Saint-Germain": {"ShortenName": "Paris", "Country": "FRA", "Points": 0},
    "PSV Eindhoven": {"ShortenName": "PSV", "Country": "NED", "Points": 0},
    "Real Madrid C.F.": {"ShortenName": "Real Madrid", "Country": "ESP", "Points": 0},
    "ŠK Slovan Bratislava": {"ShortenName": "S. Bratislava", "Country": "SVK", "Points": 0},
    "FC Salzburg": {"ShortenName": "Salzburg", "Country": "AUT", "Points": 0},
    "FC Shakhtar Donetsk": {"ShortenName": "Shakhtar", "Country": "UKR", "Points": 0},
    "AC Sparta Praha": {"ShortenName": "Sparta Praha", "Country": "CZE", "Points": 0},
    "Sporting Clube de Portugal": {"ShortenName": "Sporting CP", "Country": "POR", "Points": 0},
    "SK Sturm Graz": {"ShortenName": "Sturm Graz", "Country": "AUT", "Points": 0},
    "VfB Stuttgart": {"ShortenName": "Stuttgart", "Country": "GER", "Points": 0},
    "BSC Young Boys": {"ShortenName": "Young Boys", "Country": "SUI", "Points": 0}
}
